<?php

declare(strict_types=1);

namespace Infocyph\InterMix\DI\Support;

use Infocyph\InterMix\DI\Container;
use Infocyph\InterMix\Internal\AtomicFileWriter;
use ReflectionException;

final class PreloadGenerator
{
    /**
     * Generate a preload file at the given path, containing a list of class files
     * to include. The preload file is generated by scanning the container's
     * definitions and extracting the class names. The resulting file can be used
     * to preload classes in a production environment.
     *
     * @throws ReflectionException
     */
    public function generate(Container $container, string $filePath): void
    {
        $repo = $container->getRepository();

        $classes = array_keys($repo->getClassResource());

        foreach ($repo->getFunctionReference() as $def) {
            if (is_string($def) && class_exists($def)) {
                $classes[] = $def;
            } elseif (is_array($def) && isset($def[0]) && is_string($def[0]) && class_exists($def[0])) {
                $classes[] = $def[0];
            }
        }

        $paths = [];
        foreach (array_unique($classes) as $fqcn) {
            $f = (ReflectionResource::getClassReflection($fqcn))->getFileName();
            if ($f) {
                $paths[$f] = true;
            }
        }

        $list = var_export(array_keys($paths), true);
        $code = <<<PHP
            <?php

            declare(strict_types=1);

            foreach ($list as \$file) {
                require_once \$file;
            }
            PHP;

        AtomicFileWriter::write($filePath, $code);
    }
}
